datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@10.30.101.116:1521:orcdev
  username: DEV_NL_BRICKPARKING
  password: DEV_NL_BRICKPARKING

tasks:
  customer-activation-delay: 5000
  vehicle-profile-validation-delay: 300000
  transpondercard-validation-cron: 0 0 6 1/1 * ? # daily at 6 am (system time)
  sleeve-validation-cron: 0 0 6 1/1 * ? # daily at 6 am (system time)
  qparkcard-validation-cron: 0 0 6 1/1 * ? # daily at 6 am (system time)
  card-pool-assessment-cron: 0 30 6 1/1 * ? # daily at 6:30 am (system time)

mail:
  host: 127.0.0.1

ordervalidation:
  thresholds:
    priceEurocent: 5000
    amount: 20

customervalidation:
  thresholds:
    initialOrderAmount: 20

adminEmail: development@brickparking.com
mutator: BATCH v. ${project.version}

---

spring:
  profiles: acceptance

mail:
  host: ybmail

datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: >
        jdbc:oracle:thin:@(DESCRIPTION = (FAILOVER = ON)(LOAD_BALANCE = ON)(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = telepay)(FAILOVER_MODE=(TYPE=select)(METHOD=basic))))
  username: test_nl_brickparking
  password: test_nl_brickparking

---

spring:
  profiles: production

adminEmail: beheer@brickparking.com
