datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@yb-oradev:1521:orcl
  username: dev_nl_brickparking
  password: dev_nl_brickparking

tasks:
  customer-activation-delay: 5000

mail:
  host: 127.0.0.1

mutator: BATCH v. ${project.version}

---

spring:
  profiles: acceptance

mail:
  host: ybmail

datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: >
        jdbc:oracle:thin:@(DESCRIPTION = (FAILOVER = ON)(LOAD_BALANCE = ON)(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = telepay)(FAILOVER_MODE=(TYPE=select)(METHOD=basic))))
  username: test_nl_brickparking
  password: test_nl_brickparking
