datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@yb-oradev:1521:orcl
  username: dev_nl_brickparking
  password: dev_nl_brickparking

spring:
  thymeleaf:
    cache: false

mail:
  host: 127.0.0.1

ldap:
  enabled: true
  url: ldaps://vm-dc-01:636
  userDn: CN=ldap_user,CN=Users,DC=waysis,DC=local
  password: ldap_user

orderexport:
  path: /tmp
  # schedule card order export per product group
  # numeric key corresponds to product group id
  schedule:
    1: 0 0 6 1/1 * ?
    2: 0 0 6 1/1 * ?
    3: 0 0 6 1/1 * ?

mutator: ADMIN

---

spring:
  profiles: test

ldap:
  enabled: false

---

spring:
  profiles: acceptance

server:
  contextPath: /brickwall

mail:
  host: ybmail

datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: >
        jdbc:oracle:thin:@(DESCRIPTION = (FAILOVER = ON)(LOAD_BALANCE = ON)(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.4)(PORT = 1521))
        (CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = telepay)(FAILOVER_MODE=(TYPE=select)(METHOD=basic))))
  username: test_nl_brickparking
  password: test_nl_brickparking
