datasource:
  driverClassName: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@yb-oradev:1521:orcl
  username: dev_nl_brickparking
  password: dev_nl_brickparking

activation:
  delay: 5000

---

spring:
  profiles: test
  # for tests we use the built-in spring datasource
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=Oracle
