package nl.yellowbrick.database;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

// functions exposed to h2 database
public class H2Functions {

    private static final DateFormat ORACLE_DATE_FORMAT = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");

    // builds compatibility with Oracle's TO_DATE
    // example call:
    // TO_DATE ('05/16/2013 11:33:36', 'MM/DD/YYYY HH24:MI:SS')
    public static Date toDate(String date, String dateFormat) throws ParseException {
        // we can safely ignore the passed-in date format generated by TOAD
        return ORACLE_DATE_FORMAT.parse(date);
    }
}
