CREATE TABLE CUSTOMER
(
   BILLINGAGENTIDFK      NUMBER (8, 0),
   CUSTOMERID            NUMBER (8, 0),
   CUSTOMERNR            VARCHAR2 (10),
   BUSINESS              CHAR (1),
   ACCOUNTNR             VARCHAR2 (35),
   ACCOUNTCITY           VARCHAR2 (50),
   EXPIRYDATE            CHAR (4),
   VALIDATIONCODE        CHAR (3),
   GENDER                CHAR (1),
   BUSINESSNAME          VARCHAR2 (100),
   LASTNAME              VARCHAR2 (35),
   FIRSTNAME             VARCHAR2 (30),
   INFIX                 VARCHAR2 (20),
   INITIALS              VARCHAR2 (10),
   EMAIL                 VARCHAR2 (100),
   BUSINESSTYPEIDFK      NUMBER (2, 0),
   CUSTOMERSTATUSIDFK    NUMBER (2, 0),
   PHONENR               VARCHAR2 (20),
   FAX                   VARCHAR2 (15),
   NUMBEROFTCARDS        NUMBER (8, 0),
   NUMBEROFRTPCARDS      NUMBER (8, 0),
   PINCODE               VARCHAR2 (4),
   APPLICATIONDATE       DATE,
   MEMBERDATE            DATE,
   EXITDATE              DATE,
   CREDITLIMIT           NUMBER (6, 0),
   DATEOFBIRTH           DATE,
   ACCOUNTHOLDERNAME     VARCHAR2 (250),
   ACTIONCODE            VARCHAR2 (50),
   PRODUCTGROUP_ID       NUMBER (8, 0) DEFAULT 1,
   NUMBEROFQCARDS        NUMBER (4, 0),
   MUTATOR               VARCHAR2 (50),
   MUTATION_DATE         DATE,
   PHONENR_TCARD         VARCHAR2 (20),
   LICENSE_PLATE_TCARD   VARCHAR2 (8),
   INVOICE_EMAIL         VARCHAR2 (100),
   INVOICE_ATTN          VARCHAR2 (40),
   INVOICE_ANNOTATIONS   CHAR (1) DEFAULT 0
);

CREATE TABLE CUSTOMERADDRESS
(
   CUSTOMERADDRESSID   NUMBER (8, 0),
   CUSTOMERIDFK        NUMBER (8, 0),
   ADDRESSTYPEIDFK     NUMBER (2, 0),
   ADDRESS             VARCHAR2 (35),
   HOUSENR             VARCHAR2 (10),
   SUPPLEMENT          VARCHAR2 (10),
   POBOX               VARCHAR2 (15),
   ZIPCODE             VARCHAR2 (10),
   CITY                VARCHAR2 (50),
   COUNTRYCODE         VARCHAR2 (3),
   EXTRAINFO           VARCHAR2 (100),
   MUTATOR             VARCHAR2 (50),
   MUTATION_DATE       DATE
);

CREATE TABLE PRODUCT_GROUP
(
   ID                   NUMBER (8, 0),
   DESCRIPTION          VARCHAR2 (100),
   INTERNAL_CARD_PROV   CHAR (1) DEFAULT 0,
   MUTATOR              VARCHAR2 (50),
   MUTATION_DATE        DATE,
   ANNOTATIONS_MAX      NUMBER (8, 0) DEFAULT 8,
   START_DATE           DATE DEFAULT TRUNC (SYSDATE),
   END_DATE             DATE DEFAULT NULL
);
