DROP SCHEMA IF EXISTS WEBAPP CASCADE;
SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SCHEMA WEBAPP;


CREATE PROCEDURE WEBAPP.CustomerValidateMembership(IN P1 INT, IN P2 VARCHAR(50), IN P3 INT, IN P4 INT, IN P5 INT, IN P6 INT, IN P7 INT, IN P8 INT, IN P9 INT, IN P10 INT, IN P11 INT, IN P12 INT, IN P13 VARCHAR(50), IN P14 VARCHAR(60), IN P15 VARCHAR(60), OUT P16 INT)
SPECIFIC P1 LANGUAGE JAVA DETERMINISTIC MODIFIES SQL DATA EXTERNAL NAME 'CLASSPATH:nl.yellowbrick.data.database.Functions.customerValidateMembership';

CREATE PROCEDURE WEBAPP.saveSignupSpecialRate(IN P1 INT)
SPECIFIC P2 LANGUAGE JAVA DETERMINISTIC MODIFIES SQL DATA EXTERNAL NAME 'CLASSPATH:nl.yellowbrick.data.database.Functions.saveSignupSpecialRate';

CREATE PROCEDURE WEBAPP.cardorderupdate(IN P1 INT, IN P2 VARCHAR(255), IN P3 INT, IN P4 INT)
SPECIFIC P3 LANGUAGE JAVA DETERMINISTIC MODIFIES SQL DATA EXTERNAL NAME 'CLASSPATH:nl.yellowbrick.data.database.Functions.cardOrderUpdate';

CREATE PROCEDURE WEBAPP.CardOrderValidate(IN P1 INT, IN P2 INT, IN P3 INT, IN P4 VARCHAR(255), OUT P5 INT)
SPECIFIC P4 LANGUAGE JAVA DETERMINISTIC MODIFIES SQL DATA EXTERNAL NAME 'CLASSPATH:nl.yellowbrick.data.database.Functions.cardOrderValidate';
